### PR TITLE
If directory is empty exit 0

### LINKED ISSUE #156: Empty volume causes restic mover to get stuck
**Describe the bug**
* Restic generates an error if it's told to backup an empty directory. This causes the mover pod to error and get repeatedly restarted.
* Once some data is placed into the volume, this error condition should resolve, but it does not because the initial snapped/cloned volume is not recreated until a sync completes.
* Since a sync never completes, the temporary data volume is never recreated

**Steps to reproduce**
Create a replicationsource using the restic mover w/ a copyMethod of Snapshot or Clone, and provide a source volume that is empty (a PVC w/ no data in it)

**Expected behavior**
Once data is placed in the volume, backups should start being created correctly

**Actual results**
Restic/scribe gets stuck indefinitely

**Additional context**
Workaround:
- Delete the temporary data volume (and snapshot, if applicable) that Scribe is using
- Delete the mover job

### PR DESCRIPTION
**Pull request by cooktheryan**
Signed-off-by: Ryan Cook <rcook@redhat.com>

**Describe what this PR does**
Resolves an issue where Restic cannot handle empty directories. Restic as its currently designed can't deal with empty directories. We should just skip them until there are contents.

**Is there anything that requires special attention?**
No

**Related issues:**
closes #156

### CODE REVIEW

**Comment by cooktheryan** [comment]
I had to put the ignore of the check into place. Commit a0ab0bc would check for data in "/data" which would cause the check to fail and backups to never occr

File: mover-restic/entry.sh [hunk 1]
```diff
@@ -26,6 +26,15 @@ function check_var_defined {
     fi
 }
 
+function check_contents {
+echo "== Checking directory for content ==="
+# shellcheck disable=SC2086
+if [ -z "$(ls -A ${DATA_DIR})" ]; then
```
Comment (JohnStrunk) [inline mover-restic/entry.sh:32]: Perhaps there's something strange going on w/ putting it all in the test?
```bash
$ EDIR=/home/jstrunk/src/backube/scribe/empty
$ R="$(ls -A "${EDIR}")"
$ $([ -z "$R" ])
$ echo $?
0
$ EDIR=/home/jstrunk/src/backube/scribe
$ R="$(ls -A "${EDIR}")"
$ $([ -z "$R" ])
$ echo $?
1
```
While it doesn't need to be quoted based on the current usage (it's always `/data`), it really should be in case we end up w/ a space in there at some point.

Also, please fix the indenting of the function.

Comment (JohnStrunk) [reply mover-restic/entry.sh]: Sorry, I don't think I was clear. I didn't mean to hardcode `/data`. That path is determined by the operator, so it may change in the future. I was trying to suggest breaking the line up into something like:
```bash
DIR_CONTENTS="$(ls -A "${DATA_DIR}")"
if [ -z "${DIR_CONTENTS}" ]; then
```
...since it would provide the proper quoting of the path and avoid the need to have the shellcheck ignore. (Not that I understand why the original quoted form, putting it all in the test wouldn't work)

**Comment by cooktheryan** [comment]
```
Testing mandatory env variables
== Checking directory for content ===
== Directory is empty skipping Backup ===
```


```
== Checking directory for content ===
== Initialize Dir =======
=== Starting backup ===
/data /
no parent snapshot found, will read all files
[0:00] 0 files 0 B, total 1 files 6 B, 0 errors

Files:          11 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 3.801 KiB

processed 11 files, 66 B in 0:00
snapshot 0e1632a7 saved
/
=== Starting forget ===
Applying Policy: keep 1 hourly, 1 daily, 1 weekly, 1 monthly, 1 yearly snapshots
keep 1 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
------------------------------------------------------------------------------
0e1632a7  2021-06-09 23:39:01  scribe                  hourly snapshot   /data
                                                       daily snapshot
                                                       weekly snapshot
                                                       monthly snapshot
                                                       yearly snapshot
------------------------------------------------------------------------------
1 snapshots

=== Done ===
```

**Review by JohnStrunk — APPROVED** [review]
